### ISSUE TITLE
Support open graph and twitter meta tags

### ISSUE THREAD

**Issue by dzikoysk** [panda-lang/pandasite#17]

**Comment by wvffle** [comment]
Reference:
https://github.com/joshbuchea/HEAD#facebook-open-graph
https://github.com/joshbuchea/HEAD#twitter-card

**Comment by wvffle** [comment]
https://github.com/nuxt/vue-meta/issues/141

**Comment by dzikoysk** [comment]
Resolved in https://github.com/panda-lang/pandasite/commit/64b237a0acbb23e31f2c2e3b8f828985c1020184
